apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argo-app
    version: v1
  name: argo-app
  namespace: argo-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: argo-app
        version: v1
      name: argo-app
      namespace: argo-space
    spec:
      containers:
        - image: yashdock90/argotest:v1
          name: argotest
    imagePullPolicy: IfNotPresent
