apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: app-rollout
spec:
  replicas: 5
  selector:
    matchLabels:
      app: argo-app
      version: v1
  template:
    metadata:
      labels:
        app: argo-app
        version: v1
    spec:
      containers:
        - name: argotest
          image: yashdock90/argotest-flask:v2
          ports:
            - name: tcp
              containerPort: 5000
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
        - setWeight: 20
        - pause:
            duration: "40s"
        - setWeight: 50
        - pause:
            duration: "30s"
